Merge into master #89670
eea/eea.sparql pull request #3
Opened 2018-03-09 10:23 UTC by Petchesi-Iulian

Multiple tickets:

#89563
#91780
#89670

2018-03-14 20:07 UTC, avoinea requested changes

2018-03-14 20:07 UTC, avoinea commented on eea/sparql/content/events.py
> +        type='info')
Please fix `No new line at the end of file`

2018-03-22 08:52 UTC, avoinea submitted a review, later dismissed

2018-03-22 13:53 UTC, zotya approved these changes
everything seems ok

2018-03-22 13:53 UTC, merged